baseURL = "https://lispysnake.com/"
languageCode = "en-gb"
title = "Lispy Snake, Ltd."
enableRobotsTXT = true
canonifyURLs = true
author = ["Ikey Doherty"]
paginate = 4

[params]

    CompanyRegistration = "12179508"
    CompanyAddress = "International House, 24 Holborn Viaduct, London, United Kingdom, EC1A 2BN"
    CompanyEmail = "info@lispysnake.com"
    SocialGithub = "https://github.com/lispysnake"
    SocialTwitter = "https://twitter.com/LispySnakeLtd"
    SocialMastodon = "https://mastodon.cloud/@lispysnake"

[permalinks]
    blog = "/blog/:year/:month/:day/:title/"

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        disable = true
    [privacy.instagram]
        disable = true
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
    [privacy.youtube]
        privacyenhanced = true

[taxonomies]
    author = "authors"
    tag = "tags"
    category = "categories"
